FROM python:3

RUN pip3 install pyTelegramBotAPI
RUN pip3 install python-telegram-bot
RUN pip3 install mysql-connector-python
RUN pip3 install pillow
RUN pip3 install qrcode

WORKDIR /bot

CMD [ "python3", "-u", "./live_update.py" ]
